losses_dir: "./results/pythia-70m-full/losses"
dataset_name: "TIGER-Lab/MathInstruct"
dataset_cutoff: 80000
n_samples: 5000
num_epochs: 3
algorithm: "avg_loss_select"
output_file: "./results/data/70m-avg.json"