losses_dir: "./results/pythia-70M-full/losses"
dataset_name: "TIGER-Lab/MathInstruct"
dataset_cutoff: 120000
n_samples: 30000
num_epochs: 3
algorithm: "overall_loss_decrease_select"
output_file: "./results/data/70M-overall.json"