model_path: "EleutherAI/pythia-410m-deduped"
dataset_name: "./results/data/70M-overall.json"
output_dir: "./results/pythia-410M-overall"
num_train_epochs: 3
save_steps: 999999
curriculum_method: true
