full_data_path: TIGER-Lab/MathInstruct
model_name_or_path: EleutherAI/pythia-410m-deduped  # path to pretrained foundation llm
cache_dir: ./cache
model_max_length: 512
schedule_name: Full
result_dir_name: pythia-410m_cirriculum_full
train_args:
  optim: adamw_torch
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 8
  eval_strategy: "no"
  save_strategy: "steps"
  save_steps: 50
  save_total_limit: 12
  learning_rate: 2.0e-5
  weight_decay: 0.
  warmup_ratio: 0.03
  lr_scheduler_type: cosine
  logging_steps: 1
  bf16: TRUE
  tf32: TRUE
  group_by_length: TRUE
  full_determinism: TRUE
  seed: 42
